package com.quanta.demo0.service.Impl;


import cn.hutool.core.bean.BeanUtil;
import cn.hutool.core.util.RandomUtil;
import com.alibaba.fastjson.JSONObject;

import com.quanta.demo0.constant.JwtClaimsConstant;
import com.quanta.demo0.constant.RedisConstants;
import com.quanta.demo0.dto.UserAuthDTO;
import com.quanta.demo0.dto.UserInfoDTO;
import com.quanta.demo0.dto.UserLoginDTO;
import com.quanta.demo0.entity.BaseContext;
import com.quanta.demo0.entity.User;
import com.quanta.demo0.entity.UserAuth;
import com.quanta.demo0.entity.UserAuthInfo;
import com.quanta.demo0.enums.AuditStatus;
import com.quanta.demo0.enums.UserAuthDisplayStatus;
import com.quanta.demo0.exception.*;
import com.quanta.demo0.mapper.ContentMapper;
import com.quanta.demo0.mapper.FollowMapper;
import com.quanta.demo0.mapper.UserMapper;
import com.quanta.demo0.properties.WeChatProperties;
import com.quanta.demo0.service.UserService;
import com.quanta.demo0.utils.HttpClientUtil;
import com.quanta.demo0.utils.JwtUtil;
import com.quanta.demo0.utils.SensitiveWordChecker;
import com.quanta.demo0.vo.UserAuthStatusVO;
import com.quanta.demo0.vo.UserInfoVO;
import com.quanta.demo0.vo.UserProfileVO;
import io.jsonwebtoken.Claims;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;


import static com.quanta.demo0.constant.RedisConstants.LOGIN_USER_KEY;
import static com.quanta.demo0.constant.SystemConstant.USER_NICK_NAME_PREFIX;

/**
 * 用户域服务实现类。
 *
 * 核心职责：
 * 1. 处理用户登录、资料维护、个人主页数据聚合等核心用户能力；
 * 2. 承接身份认证申请与状态查询，驱动用户认证生命周期；
 * 3. 协调微信登录、JWT、Redis 会话等鉴权相关基础组件。
 *
 * 设计说明：
 * - 以数据库为权威源，Redis 用于会话与热点数据加速；
 * - 对外部接口调用与敏感校验做统一封装，降低业务层耦合。
 */
@Slf4j
@Service
public class UserServiceImpl implements UserService {


    // 微信服务接口
    public final static String WX_LOGIN = "https://api.weixin.qq.com/sns/jscode2session";

    @Autowired
    private WeChatProperties weChatProperties;
    @Autowired
    private UserMapper userMapper;
    @Autowired
    private SensitiveWordChecker sensitiveWordChecker;
    @Autowired
    private StringRedisTemplate stringRedisTemplate;
    @Autowired
    private FollowMapper followMapper;
    @Autowired
    private ContentMapper contentMapper;


    // 获取或创建测试用户
    private User getOrCreateTestUser(String openid, String nickName) {
        User user = userMapper.getByOpenid(openid);
        if (user == null) {
            user = User.builder()
                    .openid(openid)
                    .nickName(nickName)
                    .createTime(LocalDateTime.now())
                    .updateTime(LocalDateTime.now())
                    .build();
            userMapper.insert(user);
        }
        return user;
    }


    // 校验并清理昵称
    private String sanitizeLoginNickName(String nickName) {
        if (nickName == null || nickName.trim().isEmpty()) {
            return null;
        }
        nickName = nickName.trim();
        if (nickName.length() > 20) {
            throw new LoginFailedException("昵称不能超过 20 个字符");
        }
        return sensitiveWordChecker.replaceSensitiveWords(nickName);
    }


    // 校验并清理头像 URL
    private String sanitizeLoginAvatarUrl(String avatarUrl) {
        if (avatarUrl == null || avatarUrl.trim().isEmpty()) {
            return null;
        }
        avatarUrl = avatarUrl.trim();
        if (!avatarUrl.startsWith("http://") && !avatarUrl.startsWith("https://")) {
            throw new LoginFailedException("头像 URL 格式不正确");
        }
        return avatarUrl;
    }

    private boolean isAutoGeneratedNickName(String nickName) {
        return nickName == null || nickName.isEmpty() || nickName.startsWith(USER_NICK_NAME_PREFIX);
    }

    /** 联调 mock 账号的默认昵称，允许登录时用用户填写的昵称覆盖 */
    private boolean isPlaceholderNickName(String nickName) {
        return isAutoGeneratedNickName(nickName)
                || "测试用户".equals(nickName)
                || "测试用户B".equals(nickName);
    }

    /**
     * 登录时同步微信授权的昵称/头像到数据库
     * 业务规则：
     * - 新用户：直接写入微信授权的昵称和头像
     * - 老用户：仅在昵称为默认昵称（未自定义）或头像为空时，才用授权信息补全，避免覆盖用户已自定义的资料
     * 执行步骤：
     * 1. 清理并校验昵称和头像URL（过滤敏感词、非法字符）
     * 2. 若两者均为空则直接返回，无需更新
     * 3. 构建更新对象，根据 isNewUser 标志执行不同策略：
     *    - 新用户：直接设置昵称和头像
     *    - 老用户：判断是否为默认昵称或头像为空，满足条件才更新
     * 4. 若有字段发生变更，执行数据库更新
     * 
     * @param user 当前用户对象（用于判断是否为默认昵称/头像为空）
     * @param userLoginDTO 微信登录请求DTO（包含授权后的昵称和头像）
     * @param isNewUser 是否为新注册用户
     */
    private void syncWeChatProfileOnLogin(User user, UserLoginDTO userLoginDTO, boolean isNewUser) {
        String nickName = sanitizeLoginNickName(userLoginDTO.getNickName());
        String avatarUrl = sanitizeLoginAvatarUrl(userLoginDTO.getAvatarUrl());
        if (nickName == null && avatarUrl == null) {
            return;
        }

        // 构建更新对象
        User update = User.builder().id(user.getId()).updateTime(LocalDateTime.now()).build();
        boolean changed = false;


        // 新用户直接写入昵称和头像
        if (isNewUser) {
            if (nickName != null) {
                user.setNickName(nickName);
                update.setNickName(nickName);
                changed = true;
            }
            if (avatarUrl != null) {
                user.setAvatarUrl(avatarUrl);
                update.setAvatarUrl(avatarUrl);
                changed = true;
            }
            // 老用户仅在资料未完善时用授权信息补全
        } else {
            if (nickName != null && isPlaceholderNickName(user.getNickName())) {
                user.setNickName(nickName);
                update.setNickName(nickName);
                changed = true;
            }
            if (avatarUrl != null && (user.getAvatarUrl() == null || user.getAvatarUrl().trim().isEmpty())) {
                user.setAvatarUrl(avatarUrl);
                update.setAvatarUrl(avatarUrl);
                changed = true;
            }
        }

        if (changed) {
            userMapper.updateById(update);
        }
    }

    /**
     * 微信登录
     * 1.调用微信接口服务，用 code 换取 openid
     * 2.新用户入库；若请求携带授权后的 nickName/avatarUrl 则一并写入
     * 3.老用户仅在资料未完善时用授权信息补全
     */
    @Override
    public User weChatLogin(UserLoginDTO userLoginDTO) {

       //参数校验
        String code = userLoginDTO == null ? null : userLoginDTO.getCode();
        if (code == null || code.trim().isEmpty()) {
            throw new LoginFailedException("微信登录凭证不能为空");
        }
        code = code.trim();
        // 测试模式：当code为"test"时，直接生成测试用户
        if ("test".equals(code)) {
            User user = userMapper.getByOpenid("test_openid_123456");
            boolean isNewUser = user == null;
            if (isNewUser) {
                user = getOrCreateTestUser("test_openid_123456", "测试用户");
            }
            syncWeChatProfileOnLogin(user, userLoginDTO, isNewUser);
            return user;
        }
        if ("test2".equals(code)) {
            User user = userMapper.getByOpenid("test_openid_2");
            boolean isNewUser = user == null;
            if (isNewUser) {
                user = getOrCreateTestUser("test_openid_2", "测试用户B");
            }
            syncWeChatProfileOnLogin(user, userLoginDTO, isNewUser);
            return user;
        }
        // 1. 调用微信接口服务，获取当前微信用户信息
        Map<String, String> map = new HashMap<>();
        map.put("appid", weChatProperties.getAppid());
        map.put("secret", weChatProperties.getSecret());
        map.put("js_code", userLoginDTO.getCode());
        map.put("grant_type", "authorization_code");
//        // 打印请求参数（用于调试）
//        System.out.println("=== 微信登录请求参数 ===");
//        System.out.println("appid: " + weChatProperties.getAppid());
//        System.out.println("secret: " + weChatProperties.getSecret());
//        System.out.println("code: " + userLoginDTO.getCode());
        String json = HttpClientUtil.doGet(WX_LOGIN, map);
//        // 打印微信返回结果
//        System.out.println("=== 微信返回结果 ===");
//        System.out.println(json);
       //2.解析JSON字符串
        JSONObject jsonObject;
        try {
            jsonObject = JSONObject.parseObject(json);
        } catch (Exception e) {
            log.error("微信登录返回非JSON，body={}", json);
            throw new LoginFailedException("微信登录失败：响应格式异常");
        }
        String openid = jsonObject.getString("openid");
        // 检查是否有错误码
        Integer errcode = jsonObject.getInteger("errcode");
        String errmsg = jsonObject.getString("errmsg");
        if (errcode != null) {
            log.error("微信登录失败，errcode={}, errmsg={}", errcode, errmsg);
            throw new LoginFailedException("微信登录失败：" + errmsg);
        }
        //判断是否为空
        if (openid == null) {
            log.error("微信登录失败，openid为空，完整返回：{}", json);
            throw new LoginFailedException("微信登录失败");
        }
        //3.判断当前用户是否为新用户，如果是就创建新用户
        User user = userMapper.getByOpenid(openid);
        boolean isNewUser = user == null;
        String weChatNickName = sanitizeLoginNickName(userLoginDTO.getNickName());
        String weChatAvatarUrl = sanitizeLoginAvatarUrl(userLoginDTO.getAvatarUrl());

        if (isNewUser) {
            String nickName = weChatNickName != null
                    ? weChatNickName
                    : USER_NICK_NAME_PREFIX + RandomUtil.randomString(8);
            user = User.builder()
                    .openid(openid)
                    .nickName(nickName)
                    .avatarUrl(weChatAvatarUrl)
                    .createTime(LocalDateTime.now())
                    .updateTime(LocalDateTime.now())
                    .build();
            userMapper.insert(user);
        } else {
            syncWeChatProfileOnLogin(user, userLoginDTO, false);
        }
        //4.返回用户信息
        return user;
    }


    /**
     * 用户认证身份
     * 1.参数校验：认证信息不能为空，认证类型、真实姓名、学校ID不能为空
     * 2.获取当前用户认证信息
     * 3.首次认证，直接新增
     * 4.如果用户被驳回，可重新认证，更新认证信息，重置审核状态为待审核，清空审核备注和审核时间
     * 5.待审核，已通过，禁止重新认证
     */
    @Override
    public UserAuth addUserAuth(UserAuthDTO userAuthDTO) {

        //1.参数校验
        if (userAuthDTO == null) {
            throw new AuthFailedException("认证参数不能为空");
        }
        if (userAuthDTO.getIdentityType() == null ||
                userAuthDTO.getRealName() == null || userAuthDTO.getRealName().trim().isEmpty() ||
                userAuthDTO.getSchoolId() == null || userAuthDTO.getSchoolId().trim().isEmpty() ||
                userAuthDTO.getQuantaBatch() == null || userAuthDTO.getQuantaBatch().trim().isEmpty() ||
                userAuthDTO.getQuantaDepartment() == null || userAuthDTO.getQuantaDepartment().trim().isEmpty()) {
            throw new AuthFailedException("认证信息不完整");
        }
        //2.获取当前用户认证信息
        Long userId = BaseContext.getCurrentId();
        UserAuth userAuth = userMapper.getUserAuthByUserId(userId);
        //3.首次认证，直接新增
        if (userAuth == null) {
            //1.复制到实体类
            userAuth = BeanUtil.copyProperties(userAuthDTO, UserAuth.class);
            //2.补全字段
            userAuth.setUserId(userId);
            userAuth.setAuditStatus(AuditStatus.PENDING.getCode());
            userAuth.setCreateTime(LocalDateTime.now());
            userAuth.setUpdateTime(LocalDateTime.now());
            userMapper.insertUserAuth(userAuth);
            syncUserAuthDisplayStatus(userId, UserAuthDisplayStatus.PENDING);
            return userAuth;
        }
        //3.如果用户被驳回，可重新认证
        if (Objects.equals(userAuth.getAuditStatus(), AuditStatus.REJECTED.getCode())) {
            // 允许更新认证信息
            userAuth.setIdentityType(userAuthDTO.getIdentityType());
            userAuth.setRealName(userAuthDTO.getRealName());
            userAuth.setSchoolId(userAuthDTO.getSchoolId());
            userAuth.setQuantaBatch(userAuthDTO.getQuantaBatch());
            userAuth.setQuantaDepartment(userAuthDTO.getQuantaDepartment());
            userAuth.setAuditStatus(AuditStatus.PENDING.getCode());  // 重置为待审核
            userAuth.setAuditRemark(null);
            userAuth.setAuditTime(null);
            userAuth.setUpdateTime(LocalDateTime.now());
            userMapper.updateUserAuth(userAuth);
            syncUserAuthDisplayStatus(userId, UserAuthDisplayStatus.PENDING);
            return userAuth;
        }
        //待审核，已通过，禁止重新认证
        if (Objects.equals(userAuth.getAuditStatus(), AuditStatus.APPROVED.getCode())) {
            throw new AuthFailedException("用户已经认证过了");
        }
       if (Objects.equals(userAuth.getAuditStatus(), AuditStatus.PENDING.getCode())) {
            throw new AuthFailedException("用户正在审核中，不能重新认证");
        }
       throw new AuthFailedException("当前状态不能重新认证");
    }


    /**
     * 根据用户ID查询用户信息（昵称、头像URL）
     */
    @Override
    public UserInfoVO getById(Long id) {
        User user = userMapper.getById(id);
        if (user == null) {
            throw new NoFoundException("用户不存在");
        }

        // 新增：封禁用户对外不可见
        if (Integer.valueOf(1).equals(user.getAccountStatus())) {
            throw new NoFoundException("用户不存在");
        }

        UserInfoVO userInfoVO = UserInfoVO.builder()
                .nickName(user.getNickName())
                .avatarUrl(user.getAvatarUrl())
                .build();
        return userInfoVO;
    }


    /**
     * 更新用户信息(昵称、头像)
     * 昵称有敏感词需要过滤掉，替换成***
     * 昵称长度限制在1-20个字符
     * 头像URL必须以http://或https://开头
     */
    @Override
    public void updateUserInfo(UserInfoDTO userInfoDTO) {
        // 1. 校验昵称和头像不能同时为空
        if ((userInfoDTO.getNickName() == null || userInfoDTO.getNickName().trim().isEmpty()) &&
                (userInfoDTO.getAvatarUrl() == null || userInfoDTO.getAvatarUrl().trim().isEmpty())) {
            throw new UserInfoFailedException("昵称和头像不能同时为空");
        }
        // 2. 校验昵称长度（1-20 个字符）
        if (userInfoDTO.getNickName() != null && !userInfoDTO.getNickName().trim().isEmpty()) {
            String nickName = userInfoDTO.getNickName().trim();
            if (nickName.length() > 20) {
                throw new UserInfoFailedException("昵称不能超过 20 个字符");
            }
        }

        //3.校验敏感词（有的话替换成***）
        String nickName = userInfoDTO.getNickName();
        if (nickName != null && !nickName.trim().isEmpty()) {
            nickName = sensitiveWordChecker.replaceSensitiveWords(nickName);
            userInfoDTO.setNickName(nickName);
        }


        //3.校验Url
        if (userInfoDTO.getAvatarUrl() != null && !userInfoDTO.getAvatarUrl().trim().isEmpty()) {
            String avatarUrl = userInfoDTO.getAvatarUrl().trim();
            // 校验 URL 格式：必须以 http:// 或 https:// 开头
            if (!avatarUrl.startsWith("http://") && !avatarUrl.startsWith("https://")) {
                throw new UserInfoFailedException("头像 URL 格式不正确");
            }
        }
        //-----业务逻辑------


        //1.更新1用户信息
        User user = BeanUtil.copyProperties(userInfoDTO, User.class);
        user.setId(BaseContext.getCurrentId());
        user.setUpdateTime(LocalDateTime.now());
      //2.更新数据库
       int rows =  userMapper.updateById(user);
       if(rows == 0){
           throw new UserInfoFailedException("更新用户信息失败");
       }
    }


    /**
     * 获取用户认证状态
     * 1.根据用户ID查询认证信息
     * 2.用户没有认证过，返回-1，告诉前端用户没有认证过
     * 3.用户认证失败,返回认证备注
     * 4.用户认证中，返回1
     * 5.用户认证通过，返回2
     */
    @Override
    public UserAuthStatusVO getAuthStatus(Long currentId) {
        UserAuth userAuth = userMapper.getUserAuthByUserId(currentId);
        if (userAuth == null) {
            //说明用户没有认证过，返回-1,告诉前端用户没有认证过
            return UserAuthStatusVO.builder()
                    .auditStatus(AuditStatus.UNSUBMITTED.getCode())
                    .build();
        }

        if (Objects.equals(userAuth.getAuditStatus(), AuditStatus.REJECTED.getCode())) {
            //说明用户认证失败,返回认证备注
            return UserAuthStatusVO.builder()
                    .auditStatus(userAuth.getAuditStatus())
                    .auditRemark(userAuth.getAuditRemark())
                    .build();
        }
      return UserAuthStatusVO.builder()
                .auditStatus(userAuth.getAuditStatus())
                .build();
    }



    /**
     * 获取用户认证信息
     * 1.根据用户ID查询认证信息
     * 2.用户没有认证过，抛出异常
     * 3.用户认证未通过，抛出异常
     * 4.用户认证通过，返回认证信息
     */
    @Override
    public UserAuth getAuthDetail(Long currentId) {
        UserAuth userAuth = userMapper.getUserAuthByUserId(currentId);
        //判断用户是否认证过
        if (userAuth == null) {
            throw new AuthFailedException("用户认证信息不存在");
        }
        //判断用户是否认证通过
        if (!Objects.equals(userAuth.getAuditStatus(), AuditStatus.APPROVED.getCode())) {
            throw new AuthFailedException("用户认证信息未通过");
        }
        return userAuth;
    }

    /**
     * 获取用户主页信息（C 端公开字段）
     * 1. 参数校验
     * 2. 查询目标用户公开信息（过滤软删除）
     * 3. 统计关注数、粉丝数、帖子数
     * 4. 判断当前用户是否已关注目标用户
     * 5. 判断是否是当前登录用户自己
     * 6. 封装 VO 并返回
     *
     * @param targetUserId 目标用户 ID
     * @param viewerId     当前登录用户 ID
     * @return 用户主页信息
     */
    @Override
    public UserProfileVO getUserProfile(Long targetUserId, Long viewerId) {
        // 1. 参数校验
        if (targetUserId == null) {
            throw new NoFoundException("用户 ID 不能为空");
        }

        // 2. 查询目标用户公开信息（过滤软删除）
        UserAuthInfo userInfo = userMapper.selectUserAuthInfoById(targetUserId);
        if (userInfo == null) {
            throw new NoFoundException("用户不存在");
        }
        // 新增：校验目标用户是否被封禁
        if (Integer.valueOf(1).equals(userInfo.getAccountStatus())) {
            throw new NoFoundException("用户不存在");
        }

        // 3. 统计关注数、粉丝数、帖子数
        Integer followingCount = followMapper.countFollowing(targetUserId);
        Integer followerCount = followMapper.countFollowers(targetUserId);
        Integer contentCount = contentMapper.countUserPublicContents(targetUserId);

        // 4. 判断当前用户是否已关注目标用户
        Boolean isFollowed = false;
        if (viewerId != null && !viewerId.equals(targetUserId)) {
            String key = RedisConstants.FOLLOWED_KEY + viewerId;
            isFollowed = Boolean.TRUE.equals(stringRedisTemplate.opsForSet().isMember(key, targetUserId.toString()));
        }

        // 5. 判断是否是当前登录用户自己
        Boolean isSelf = viewerId != null && viewerId.equals(targetUserId);

        // 6. 展示态与 tb_user_auth 对齐（历史数据可能已通过但 auth_status 仍为 1）
        Integer authStatus = resolveAuthDisplayStatus(targetUserId, userInfo.getAuthStatus());

        // 7. 封装 VO 并返回
        return UserProfileVO.builder()
                .userId(userInfo.getUserId())
                .nickName(userInfo.getNickName())
                .avatarUrl(userInfo.getAvatarUrl())
                .authStatus(authStatus)
                .quantaDepartment(userInfo.getQuantaDepartment())
                .quantaBatch(userInfo.getQuantaBatch())
                .followingCount(followingCount != null ? followingCount : 0)
                .followerCount(followerCount != null ? followerCount : 0)
                .contentCount(contentCount != null ? contentCount : 0)
                .isFollowed(isFollowed)
                .isSelf(isSelf)
                .build();
    }

    /**
     * 退出登录
     * 2. 删除 Redis 中的 token
     * 3. 清除封禁标记（如果有）
     */

    @Override
    public void logout() {
        try {
            // 1. 解析 token 获取 userId
           Long userId=BaseContext.getCurrentId();
            // 2. 删除 Redis 中的 token
            String loginKey = LOGIN_USER_KEY + userId;
            stringRedisTemplate.delete(loginKey);

            // 3. 清除封禁标记（如果有）
            String bannedKey = RedisConstants.USER_BANNED_KEY + userId;
            stringRedisTemplate.delete(bannedKey);

            log.info("退出登录成功，userId={}", userId);
        } catch (Exception e) {
            log.error("退出登录失败，token 无效或已过期", e);

        }
    }

    /** 同步 tb_user.auth_status（展示态，见 {@link UserAuthDisplayStatus}） */
    private void syncUserAuthDisplayStatus(Long userId, UserAuthDisplayStatus displayStatus) {
        if (userId == null || displayStatus == null) {
            return;
        }
        User patch = new User();
        patch.setId(userId);
        patch.setAuthStatus(displayStatus.getCode());
        patch.setUpdateTime(LocalDateTime.now());
        userMapper.updateById(patch);
    }

    /** 按认证表 audit_status 推导主页展示态，不一致时回写 tb_user.auth_status */
    private Integer resolveAuthDisplayStatus(Long userId, Integer storedDisplayStatus) {
        UserAuth userAuth = userMapper.getUserAuthByUserId(userId);
        UserAuthDisplayStatus expected = expectedDisplayFromAuthRecord(userAuth);
        int code = expected.getCode();
        if (!Objects.equals(storedDisplayStatus, code)) {
            syncUserAuthDisplayStatus(userId, expected);
            log.warn("修复 auth_status 与认证表不一致 userId={} stored={} repaired={}",
                    userId, storedDisplayStatus, code);
        }
        return code;
    }

    private UserAuthDisplayStatus expectedDisplayFromAuthRecord(UserAuth userAuth) {
        if (userAuth == null) {
            return UserAuthDisplayStatus.NONE;
        }
        if (Objects.equals(userAuth.getAuditStatus(), AuditStatus.APPROVED.getCode())) {
            return UserAuthDisplayStatus.VERIFIED;
        }
        if (Objects.equals(userAuth.getAuditStatus(), AuditStatus.REJECTED.getCode())) {
            return UserAuthDisplayStatus.REJECTED;
        }
        if (Objects.equals(userAuth.getAuditStatus(), AuditStatus.PENDING.getCode())) {
            return UserAuthDisplayStatus.PENDING;
        }
        return UserAuthDisplayStatus.NONE;
    }
}

