#!/usr/bin/env bash
# demo0 API phase runner — curl + jq, writes env.sh and test-output/last-run.json
# Usage: ./scripts/run-phase.sh [0-1|2-3|all|0|1|2|3|4|5|6|7]
#
# Failure policy: 3 consecutive failures with the same signature (http + body.code) → pause (exit 2).
# BLOCKED cases (note prefix) do not advance the failure streak.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_TEST_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$API_TEST_DIR/test-output"
OUT_FILE="$OUT_DIR/last-run.json"
TMP_DIR="${TMPDIR:-/tmp}/demo0-api-test"
FIXTURE="$API_TEST_DIR/cases/fixtures/pixel.png"

MAX_SAME_FAIL=3
FAIL_STREAK_KEY=""
FAIL_STREAK_COUNT=0

declare -A ENV_VARS=()
declare -a RESULT_NAMES=()
declare -a RESULT_PASS=()
declare -a RESULT_HTTP=()
declare -a RESULT_CODE=()
declare -a RESULT_MSG=()
declare -a RESULT_NOTE=()

PHASE_LABEL=""

die() { echo "error: $*" >&2; exit 1; }

require_cmds() {
  local c
  for c in curl jq; do
    command -v "$c" >/dev/null 2>&1 || die "missing required command: $c"
  done
}

load_env() {
  if [[ -f "$API_TEST_DIR/env.sh" ]]; then
    # shellcheck source=/dev/null
    source "$API_TEST_DIR/env.sh"
  elif [[ -f "$API_TEST_DIR/env.example.sh" ]]; then
    echo "warn: env.sh not found, sourcing env.example.sh (tokens may be empty)" >&2
    # shellcheck source=/dev/null
    source "$API_TEST_DIR/env.example.sh"
  else
    die "missing env.sh — cp env.example.sh env.sh and configure"
  fi
  BASE_URL="${BASE_URL:-http://localhost:9191}"
  ENV_VARS[BASE_URL]="$BASE_URL"
}

mkdir -p "$OUT_DIR" "$TMP_DIR"

# Prints body_text and http on separate lines.
invoke_curl_api() {
  local name=$1 method=$2 path=$3
  local token=${4:-} json_body=${5:-} form_file=${6:-}
  local uri="${BASE_URL}${path}"
  local -a curl_args=(-s -S -w "\n__HTTP__:%{http_code}" -X "$method" "$uri")

  [[ -n "$token" ]] && curl_args+=(-H "authorization: $token")
  if [[ -n "$json_body" ]]; then
    local body_file="$TMP_DIR/${name}-body.json"
    printf '%s' "$json_body" >"$body_file"
    curl_args+=(-H "Content-Type: application/json" --data-binary "@$body_file")
  fi
  if [[ -n "$form_file" ]]; then
    curl_args+=(-F "file=@$form_file")
  fi

  local raw http body_text
  if ! raw="$(curl "${curl_args[@]}" 2>&1)"; then
    printf 'CURL_ERROR\n0\n'
    return 1
  fi

  http="$(printf '%s' "$raw" | sed -n 's/.*__HTTP__:\([0-9][0-9]*\)$/\1/p' | tail -n1)"
  body_text="$(printf '%s' "$raw" | sed 's/__HTTP__:[0-9][0-9]*$//')"
  [[ -z "$http" ]] && http="0"
  printf '%s\n%s\n' "$body_text" "$http"
}

jq_field() {
  printf '%s' "$1" | jq -r "$2" 2>/dev/null || true
}

check_fail_streak() {
  local pass=$1 http=$2 code=$3 note=$4
  if [[ "$pass" == "true" ]]; then
    FAIL_STREAK_KEY=""
    FAIL_STREAK_COUNT=0
    return 0
  fi
  if [[ "$note" == BLOCKED:* ]]; then
    return 0
  fi

  local key="http=${http}:code=${code}"
  if [[ "$key" == "$FAIL_STREAK_KEY" ]]; then
    FAIL_STREAK_COUNT=$((FAIL_STREAK_COUNT + 1))
  else
    FAIL_STREAK_KEY="$key"
    FAIL_STREAK_COUNT=1
  fi

  if (( FAIL_STREAK_COUNT >= MAX_SAME_FAIL )); then
    echo "" >&2
    echo "PAUSED: ${MAX_SAME_FAIL} consecutive failures with signature: ${FAIL_STREAK_KEY}" >&2
    echo "Fix the underlying issue, then re-run. Partial results saved to $OUT_FILE" >&2
    write_outputs "$PHASE_LABEL"
    exit 2
  fi
}

record_case() {
  local name=$1 pass=$2 http=$3 code=$4 msg=$5 note=${6:-}
  RESULT_NAMES+=("$name")
  RESULT_PASS+=("$pass")
  RESULT_HTTP+=("$http")
  RESULT_CODE+=("$code")
  RESULT_MSG+=("$msg")
  RESULT_NOTE+=("$note")
  check_fail_streak "$pass" "$http" "$code" "$note"
  local status="FAIL"
  [[ "$pass" == "true" ]] && status="PASS"
  echo "  [$status] $name HTTP=$http code=${code:-'-'} ${note:+$note}"
}

login_token() {
  local out body_text http code token
  out="$(invoke_curl_api login POST /user/login '' '{"code":"test"}')" || return 1
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  token="$(jq_field "$body_text" '.data.token')"
  if [[ "$http" == "200" && "$code" == "200" && -n "$token" ]]; then
    printf '%s' "$token"
    return 0
  fi
  return 1
}

write_env_sh() {
  local path="$API_TEST_DIR/env.sh"
  {
    echo '# auto-generated by run-phase.sh'
    echo "export BASE_URL=\"${ENV_VARS[BASE_URL]:-$BASE_URL}\""
    local k v
    for k in USER_TOKEN ADMIN_TOKEN USER_B_TOKEN USER_ID USER_B_ID \
      CONTENT_ID_PROF CONTENT_ID_LIFE QUESTION_ID ANSWER_ID COMMENT_ID \
      NOTIFICATION_ID IMAGE_URL REPORT_ID SEARCH_HISTORY_ID; do
      v="${ENV_VARS[$k]:-}"
      echo "export $k=\"$v\""
    done
  } >"$path"
  echo "env.sh updated -> $path"
}

write_outputs() {
  local phase_label=$1
  local pass_count=0 fail_count=0 i n=${#RESULT_NAMES[@]}
  for ((i = 0; i < n; i++)); do
    if [[ "${RESULT_PASS[$i]}" == "true" ]]; then
      pass_count=$((pass_count + 1))
    else
      fail_count=$((fail_count + 1))
    fi
  done

  local results_json
  results_json="$(jq -n \
    --arg phase "$phase_label" \
    --arg ts "$(date '+%Y-%m-%d %H:%M:%S')" \
    --argjson pass "$pass_count" \
    --argjson fail "$fail_count" \
    --arg base "${ENV_VARS[BASE_URL]:-$BASE_URL}" \
    --arg ut "${ENV_VARS[USER_TOKEN]:-}" \
    --arg at "${ENV_VARS[ADMIN_TOKEN]:-}" \
    --arg uid "${ENV_VARS[USER_ID]:-}" \
    --arg prof "${ENV_VARS[CONTENT_ID_PROF]:-}" \
    --arg life "${ENV_VARS[CONTENT_ID_LIFE]:-}" \
    --arg ans "${ENV_VARS[ANSWER_ID]:-}" \
    --arg img "${ENV_VARS[IMAGE_URL]:-}" \
    '{
      phase: $phase,
      timestamp: $ts,
      passCount: $pass,
      failCount: $fail,
      env: {
        BASE_URL: $base,
        USER_TOKEN: $ut,
        ADMIN_TOKEN: $at,
        USER_ID: $uid,
        CONTENT_ID_PROF: $prof,
        CONTENT_ID_LIFE: $life,
        ANSWER_ID: $ans,
        IMAGE_URL: $img
      },
      results: []
    }')"

  for ((i = 0; i < n; i++)); do
    local pass_json=false
    [[ "${RESULT_PASS[$i]}" == "true" ]] && pass_json=true
    results_json="$(printf '%s' "$results_json" | jq \
      --arg name "${RESULT_NAMES[$i]}" \
      --argjson pass "$pass_json" \
      --argjson http "${RESULT_HTTP[$i]:-0}" \
      --arg code "${RESULT_CODE[$i]}" \
      --arg msg "${RESULT_MSG[$i]}" \
      --arg note "${RESULT_NOTE[$i]}" \
      '.results += [{
        name: $name,
        pass: $pass,
        http: $http,
        code: (if $code == "" then null else ($code | tonumber? // $code) end),
        msg: (if $msg == "" then null else $msg end),
        note: (if $note == "" then null else $note end)
      }]')"
  done

  printf '%s\n' "$results_json" | jq '.' >"$OUT_FILE"
  write_env_sh
  echo "PASS=$pass_count FAIL=$fail_count -> $OUT_FILE"
}

run_phase_0_1() {
  PHASE_LABEL="0-1"
  local user_token="" admin_token=""
  local out body_text http code msg token uid

  out="$(invoke_curl_api P0-01 GET /user/info)" || true
  http="$(printf '%s' "$out" | sed -n '2p')"
  record_case P0-01 "$([[ "$http" == "401" ]] && echo true || echo false)" "$http" "" "" ""

  out="$(invoke_curl_api P0-02 POST /user/login '' '{"code":"test"}')" || true
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  msg="$(jq_field "$body_text" '.msg')"
  token="$(jq_field "$body_text" '.data.token')"
  uid="$(jq_field "$body_text" '.data.id')"
  local p0_02=false
  [[ "$http" == "200" && "$code" == "200" && -n "$token" ]] && p0_02=true
  if [[ "$p0_02" == true ]]; then
    user_token="$token"
    ENV_VARS[USER_TOKEN]="$token"
    ENV_VARS[USER_ID]="$uid"
  fi
  record_case P0-02 "$p0_02" "$http" "$code" "$msg" ""

  out="$(invoke_curl_api P1-01 POST /user/login '' '{"code":""}')" || true
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  msg="$(jq_field "$body_text" '.msg')"
  record_case P1-01 "$([[ "$code" == "400" ]] && echo true || echo false)" "$http" "$code" "$msg" ""

  out="$(invoke_curl_api P1-03 GET /user/info)" || true
  http="$(printf '%s' "$out" | sed -n '2p')"
  record_case P1-03 "$([[ "$http" == "401" ]] && echo true || echo false)" "$http" "" "" ""

  out="$(invoke_curl_api P1-04 GET /user/info invalid-token)" || true
  http="$(printf '%s' "$out" | sed -n '2p')"
  record_case P1-04 "$([[ "$http" == "401" ]] && echo true || echo false)" "$http" "" "" ""

  out="$(invoke_curl_api P1-05 GET /user/info "$user_token")" || true
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  msg="$(jq_field "$body_text" '.msg')"
  record_case P1-05 "$([[ "$http" == "200" && "$code" == "200" ]] && echo true || echo false)" "$http" "$code" "$msg" ""

  out="$(invoke_curl_api P1-06 GET '/admin/user/page?pageNum=1&pageSize=10' "$user_token")" || true
  http="$(printf '%s' "$out" | sed -n '2p')"
  local p1_06=false p1_06_note=""
  if [[ "$http" == "403" ]]; then
    p1_06=true
  elif [[ "$http" == "200" ]]; then
    p1_06_note="test user is_admin=1; run SQL is_admin=0 before P1-06 or use USER_B"
  fi
  record_case P1-06 "$p1_06" "$http" "" "" "$p1_06_note"

  out="$(invoke_curl_api P0-03 POST /user/login '' '{"code":"test"}')" || true
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  msg="$(jq_field "$body_text" '.msg')"
  token="$(jq_field "$body_text" '.data.token')"
  local p0_03=false p0_03_note=""
  [[ "$code" == "200" && -n "$token" ]] && p0_03=true
  if [[ "$p0_03" == true ]]; then
    admin_token="$token"
    user_token="$token"
    ENV_VARS[ADMIN_TOKEN]="$token"
    ENV_VARS[USER_TOKEN]="$token"
  else
    p0_03_note="need: UPDATE tb_user SET is_admin=1 WHERE openid=test_openid_123456"
  fi
  record_case P0-03 "$p0_03" "$http" "$code" "$msg" "$p0_03_note"

  if [[ -n "$admin_token" ]]; then
    out="$(invoke_curl_api P1-07 GET '/admin/user/page?pageNum=1&pageSize=10' "$admin_token")" || true
    body_text="$(printf '%s' "$out" | sed -n '1p')"
    http="$(printf '%s' "$out" | sed -n '2p')"
    code="$(jq_field "$body_text" '.code')"
    msg="$(jq_field "$body_text" '.msg')"
    record_case P1-07 "$([[ "$http" == "200" && "$code" == "200" ]] && echo true || echo false)" "$http" "$code" "$msg" ""
  fi
}

run_phase_2_3() {
  PHASE_LABEL="2-3"
  local fresh user_token admin_token prof_id life_id
  local out body_text http code msg

  fresh="$(login_token || true)"
  if [[ -n "$fresh" ]]; then
    ENV_VARS[USER_TOKEN]="$fresh"
    ENV_VARS[ADMIN_TOKEN]="$fresh"
  fi
  user_token="${ENV_VARS[USER_TOKEN]:-}"
  admin_token="${ENV_VARS[ADMIN_TOKEN]:-}"

  if [[ -f "$FIXTURE" ]]; then
    out="$(invoke_curl_api P2-01 POST /common/upload "$user_token" '' "$FIXTURE")" || true
    body_text="$(printf '%s' "$out" | sed -n '1p')"
    http="$(printf '%s' "$out" | sed -n '2p')"
    code="$(jq_field "$body_text" '.code')"
    msg="$(jq_field "$body_text" '.msg')"
    local url p2_01=false note=""
    url="$(jq_field "$body_text" '.data')"
    [[ "$code" == "200" && -n "$url" && "$url" != "null" ]] && p2_01=true
    if [[ "$p2_01" == true ]]; then
      ENV_VARS[IMAGE_URL]="$url"
    else
      note="BLOCKED: OSS"
    fi
    record_case P2-01 "$p2_01" "$http" "$code" "$msg" "$note"
  fi

  out="$(invoke_curl_api P2-04 POST /content/publish "$user_token" '{"contentType":2,"title":"API-test-prof","content":"prof desc","images":[]}')" || true
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  msg="$(jq_field "$body_text" '.msg')"
  prof_id="$(jq_field "$body_text" '.data.contentId')"
  local p2_04=false p2_04_note=""
  [[ "$code" == "200" && -n "$prof_id" && "$prof_id" != "null" ]] && p2_04=true
  if [[ "$p2_04" == true ]]; then
    ENV_VARS[CONTENT_ID_PROF]="$prof_id"
    ENV_VARS[QUESTION_ID]="$prof_id"
  elif [[ "$code" == "500" ]]; then
    p2_04_note="server 500 - restart app after collectCount fix"
  fi
  record_case P2-04 "$p2_04" "$http" "$code" "$msg" "$p2_04_note"

  out="$(invoke_curl_api P2-05 POST /content/publish "$user_token" '{"contentType":1,"title":"API-test-life","content":"life desc","images":[]}')" || true
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  msg="$(jq_field "$body_text" '.msg')"
  life_id="$(jq_field "$body_text" '.data.contentId')"
  local p2_05=false
  [[ "$code" == "200" && -n "$life_id" && "$life_id" != "null" ]] && p2_05=true
  if [[ "$p2_05" == true ]]; then ENV_VARS[CONTENT_ID_LIFE]="$life_id"; fi
  record_case P2-05 "$p2_05" "$http" "$code" "$msg" ""

  out="$(invoke_curl_api P2-06 POST /content/publish "$user_token" '{"contentType":2,"title":"","content":"ok","images":[]}')" || true
  body_text="$(printf '%s' "$out" | sed -n '1p')"
  http="$(printf '%s' "$out" | sed -n '2p')"
  code="$(jq_field "$body_text" '.code')"
  msg="$(jq_field "$body_text" '.msg')"
  record_case P2-06 "$([[ "$code" == "400" ]] && echo true || echo false)" "$http" "$code" "$msg" ""

  prof_id="${ENV_VARS[CONTENT_ID_PROF]:-}"
  life_id="${ENV_VARS[CONTENT_ID_LIFE]:-}"

  if [[ -n "$admin_token" && -n "$prof_id" ]]; then
    out="$(invoke_curl_api P3-01 GET "/admin/content/page?pageNum=1&pageSize=10&auditStatus=0" "$admin_token")" || true
    body_text="$(printf '%s' "$out" | sed -n '1p')"
    http="$(printf '%s' "$out" | sed -n '2p')"
    code="$(jq_field "$body_text" '.code')"
    msg="$(jq_field "$body_text" '.msg')"
    record_case P3-01 "$([[ "$code" == "200" ]] && echo true || echo false)" "$http" "$code" "$msg" ""

    out="$(invoke_curl_api P3-04 POST /admin/content/audit "$admin_token" "{\"contentId\":$prof_id,\"auditResult\":1}")" || true
    body_text="$(printf '%s' "$out" | sed -n '1p')"
    http="$(printf '%s' "$out" | sed -n '2p')"
    code="$(jq_field "$body_text" '.code')"
    msg="$(jq_field "$body_text" '.msg')"
    record_case P3-04 "$([[ "$code" == "200" ]] && echo true || echo false)" "$http" "$code" "$msg" ""
  fi

  if [[ -n "$admin_token" && -n "$life_id" ]]; then
    out="$(invoke_curl_api P3-05 POST /admin/content/audit "$admin_token" "{\"contentId\":$life_id,\"auditResult\":2,\"rejectReason\":\"api-reject\"}")" || true
    body_text="$(printf '%s' "$out" | sed -n '1p')"
    http="$(printf '%s' "$out" | sed -n '2p')"
    code="$(jq_field "$body_text" '.code')"
    msg="$(jq_field "$body_text" '.msg')"
    record_case P3-05 "$([[ "$code" == "200" ]] && echo true || echo false)" "$http" "$code" "$msg" ""
  fi

  if [[ -n "$prof_id" ]]; then
    out="$(invoke_curl_api P3-06 POST /answer/publish "$user_token" "{\"questionId\":$prof_id,\"content\":\"answer after audit\"}")" || true
    body_text="$(printf '%s' "$out" | sed -n '1p')"
    http="$(printf '%s' "$out" | sed -n '2p')"
    code="$(jq_field "$body_text" '.code')"
    msg="$(jq_field "$body_text" '.msg')"
    local ans_id p3_06=false
    ans_id="$(jq_field "$body_text" '.data.answerId')"
    [[ "$code" == "200" ]] && p3_06=true
    if [[ "$p3_06" == true && -n "$ans_id" && "$ans_id" != "null" ]]; then
      ENV_VARS[ANSWER_ID]="$ans_id"
    fi
    record_case P3-06 "$p3_06" "$http" "$code" "$msg" ""
  fi

  if [[ -n "$life_id" ]]; then
    out="$(invoke_curl_api P3-07 POST /answer/publish "$user_token" "{\"questionId\":$life_id,\"content\":\"life no answer\"}")" || true
    body_text="$(printf '%s' "$out" | sed -n '1p')"
    http="$(printf '%s' "$out" | sed -n '2p')"
    code="$(jq_field "$body_text" '.code')"
    msg="$(jq_field "$body_text" '.msg')"
    record_case P3-07 "$([[ "$code" == "400" ]] && echo true || echo false)" "$http" "$code" "$msg" ""
  fi
}

run_phase_manual() {
  local phase=$1
  PHASE_LABEL="$phase"
  echo "Phase $phase — BASE_URL=$BASE_URL"
  echo "Run cases under: $API_TEST_DIR/cases/"
  echo "Record outcomes in: $API_TEST_DIR/RESULTS.md"
  echo "(Phases 4–7: use cases/03-read.http … 06-destructive.http; auto-runner not implemented yet)"
}

normalize_phase() {
  case "${1:-}" in
    0|1|0-1) echo "0-1" ;;
    2|3|2-3) echo "2-3" ;;
    all|4|5|6|7) echo "$1" ;;
    "") echo "" ;;
    *) echo "invalid" ;;
  esac
}

main() {
  require_cmds
  load_env

  local raw_phase="${1:-all}"
  local phase
  phase="$(normalize_phase "$raw_phase")"
  [[ "$phase" == "invalid" ]] && die "unknown phase: $raw_phase"

  echo "demo0 api-test | phase=$phase | BASE_URL=$BASE_URL"

  case "$phase" in
    0-1) run_phase_0_1 ;;
    2-3) run_phase_2_3 ;;
    all)
      run_phase_0_1
      run_phase_2_3
      ;;
    4|5|6|7)
      run_phase_manual "$phase"
      write_outputs "$phase"
      exit 0
      ;;
    *)
      echo "Usage: $0 <0-7|0-1|2-3|all>" >&2
      echo "  0-1  env & login/auth (curl+jq)" >&2
      echo "  2-3  upload, publish, admin audit" >&2
      echo "  all  phases 0-1 and 2-3" >&2
      echo "  4-7  manual (cases/*.http) — record in RESULTS.md" >&2
      exit 1
      ;;
  esac

  write_outputs "$phase"
}

main "$@"
